version: '3'

services:
    nodejs-api:
        build: 
            context: ./
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        container_name: node-api
        links:
          - mongo
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        container_name: mongodb
        volumes:
          - ./db/:/data/db

